### ISSUE TITLE
Encountered an error "undefined is not a function" at every "npm install" command

### ISSUE THREAD

**Issue by Miralo** [npm/newww#1133]
Hi! I'm encountering this error every time i need to install a package and run the "npm install" command: "undefined is not a function"

I can't understand where wrong. Here you can find the debug log.

"
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   'C:\\Users\\Myuser\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'gulp',
1 verbose cli   '-g' ]
2 info using npm@2.12.0
3 info using node@v0.12.5
4 verbose install initial load of C:\Program Files\nodejs\package.json
5 verbose readDependencies loading dependencies from C:\Program Files\nodejs\package.json
6 silly cache add args [ 'gulp', null ]
7 verbose cache add spec gulp
8 silly cache add parsed spec { raw: 'gulp',
8 silly cache add   scope: null,
8 silly cache add   name: 'gulp',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed gulp@*
10 verbose addNamed "*" is a valid semver range for gulp
11 silly addNameRange { name: 'gulp', range: '*', hasData: false }
12 silly mapToRegistry name gulp
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/gulp
16 verbose addNameRange registry:https://registry.npmjs.org/gulp not in flight; fetching
17 verbose request uri https://registry.npmjs.org/gulp
18 verbose request no auth needed
19 info attempt registry request try #1 at 10:43:29
20 verbose request id 971a515e864662b4
21 http request GET https://registry.npmjs.org/gulp
22 http 200 https://registry.npmjs.org/gulp
23 silly get cb [ 200,
23 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 silly get     etag: '"B7MRKJEM5D7CSPIJE1C58H5IN"',
23 silly get     'content-type': 'application/json',
23 silly get     'cache-control': 'max-age=60',
23 silly get     'content-length': '105173',
23 silly get     'accept-ranges': 'bytes',
23 silly get     date: 'Mon, 10 Aug 2015 08:43:29 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     age: '31',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-lhr6333-LHR',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '2',
23 silly get     'x-timer': 'S1439196209.673826,VS0,VE0',
23 silly get     vary: 'Accept' } ]
24 verbose get saving gulp to C:\Users\Myuser\AppData\Roaming\npm-cache\registry.npmjs.org\gulp\.cache.json
25 verbose stack TypeError: undefined is not a function
25 verbose stack     at calculateOwner (C:\Users\mmirandola\AppData\Roaming\npm\node_modules\npm\lib\utils\correct-mkdir.js:37:24)
25 verbose stack     at C:\Users\mmirandola\AppData\Roaming\npm\node_modules\npm\lib\utils\correct-mkdir.js:23:22
25 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
26 verbose cwd C:\Users\mmirandola
27 error Windows_NT 6.3.9600
28 error argv "node" "C:\\Users\\Myuser\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp" "-g"
29 error node v0.12.5
30 error npm  v2.12.0
31 error undefined is not a function
32 error If you need help, you may report this error at:
32 error     <https://github.com/npm/npm/issues>
33 verbose exit [ 1, true ]
"

**Comment by KenanY** [comment]
@Miralo `npm@2.12.0` was dead-on-arrival on Windows due to this bug, which was fixed in `npm@2.12.1` a little over a month ago. [Upgrading](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) should solve this issue :)

Also, issues like these are better taken to [npm/npm](https://github.com/npm/npm). This issue tracker is for issues with the website.

**Comment by aredridel** [comment]
What @KenanY said is correct.

**Comment by Miralo** [comment]
Hi, i've tried to use the automatic command line tool suggested here (https://github.com/felixrieseberg/npm-windows-upgrade) but npm give me the same error. That tool says that npm is now at the 3.2.2 version, but the error is always about the 2.12.0

**Comment by aredridel** [comment]
This is still not the right place to post about this issue -- this repo is about the npm website, not the upgrader nor npm command line tool.

However, you probably have two versions of npm installed, in different places in your path, and will need to run the other one.

**Comment by aredridel** [comment]
Feel free to make a support request against the http://github.com/npm/npm repository.
