### ISSUE TITLE
ERROR: No README data found!

### ISSUE THREAD

**Issue by shakiba** [npm/newww#867]
[This package](https://www.npmjs.com/package/deprecated) has a README file but it is not viewed.

**Comment by Pajamaman** [comment]
I'm having the same issue: https://www.npmjs.com/package/clean-html

Mine also says it's still on version 1.0.0 even though I published 1.0.1.

**Comment by stevengill** [comment]
Same issue here. 

I have a test module I published at https://www.npmjs.com/package/delete-this. It says "Sadly, this package has no readme. Go write one!".

Issue is, I do have a README.md file in the root of the module. It just says hello world in it. 

Here is the package.json file in my .npm/delete-this/1.2.3/package directory. This is the package.json that gets generated when I run npm publish.

<code>
{"name":"delete-this","version":"1.2.3","description":"Cordova Legacy Whitelist Plugin","cordova":{"platforms":["android","ios"]},"repository":{"type":"git","url":"https://git-wip-us.apache.org/repos/asf/cordova-plugin-legacy-whitelist.git"},"keywords":["cordova","whitelist","ecosystem:cordova","cordova-android","cordova-ios"],"engines":[{"name":"cordova-android","version":">=4.0.0-dev"},{"name":"cordova-ios","version":">=4.0.0-dev"}],"author":{"name":"Apache Software Foundation"},"license":"Apache 2.0","readme":"Hello World\n","readmeFilename":"README.md","gitHead":"9003be1a6862bcd3558ba786706b63eb7e3aa61a","_id":"delete-this@1.2.3","scripts":{},"_shasum":"abbb1b4bd6fcda79bdf566ca3855103b8f919a89","_from":"."}
</code>

As you can see, the "readme" key has the value "Hello World\n". 

Seems like the site isn't properly rendering it.

**Comment by stevengill** [comment]
Looks like issue was already reported at https://github.com/npm/newww/issues/866

**Comment by shakiba** [comment]
@stevengill I can see your package readme on npmjs.com.

**Comment by stevengill** [comment]
@shakiba It seems to be working for it now. Weird. Maybe delayed? The reason why I went down this rabbit hole was because the readme wasn't showing up for https://www.npmjs.com/package/cordova-plugin-whitelist. Still isn't.

**Comment by shakiba** [comment]
@stevengill Yes, it doesn't show readme file for cordova-plugin-whitelist.  In my reported case it shows "Error: No README data found!" which is the readme field in package.json and in your case it shows "Sadly, this package has no readme." because there is no readme field in package.json.

**Comment by mmalecki** [comment]
@stevengill there indeed is a delay between the package update in registry and package page on www changing its content. Looking at your package's `time` field, this could have been the cause of what you were seeing with `delete-this`.  
Also, after a chat with @zeke, we *think* that the issue with `cordova-plugin-whitelist` is closer to #622 rather than what's the root cause of @shakiba's problem.

@shakiba did this package page ever display the proper README? It appears that the content of `README.md` did not make it into our database. I'm afraid that until https://github.com/npm/newww/issues/389#issuecomment-66512696 is in place, the best solution is to republish this package.

I'm going to close this issue. We've been working on identifying all README-related issues and have created internal tracking tickets for them.

**Comment by shakiba** [comment]
It is not my project and I don't know if it has ever displayed the readme or not. I reported it because I was suspect that there may be other projects with the same issue, therefore fixing this one may fix many others.

**Comment by zeke** [comment]
I have confirmed that this is an issue in our new relational registry codebase, which is private. We are tracking it there, and will report back here when it's resolved.

**Comment by stevengill** [comment]
@zeke, let me know if I can help in any way. I think we are facing this problem with a bunch of our core cordova plugins

https://www.npmjs.com/package/cordova-plugin-camera
https://www.npmjs.com/package/cordova-plugin-device
https://www.npmjs.com/package/cordova-plugin-contacts
etc

**Comment by zeke** [comment]
Thanks @stevengill. @mmalecki is on the case.

**Comment by stevengill** [comment]
Thank you! You guys rock!

**Comment by zeke** [comment]
The problem is not in the registry after all. It's our markdown parser's strict adherence to the CommonMark markdown spec. More info at https://github.com/npm/marky-markdown/issues/42.

**Comment by hypery2k** [comment]
the issue also occurs for my plugin: https://www.npmjs.com/package/cordova-plugin-purchase

**Comment by steffansluis** [comment]
Any updates on this?
